var fs = require("fs");  
var c = "'use client';"   
c += String.fromCharCode(10) + "import { useState, useEffect } from 'react';"  
c += String.fromCharCode(10) + "import dynamic from 'next/dynamic';"  
c += String.fromCharCode(10) + "const RedocStandalone = dynamic(() => import('redoc').then(mod => mod.RedocStandalone), { ssr: false });"  
c += String.fromCharCode(10) + "export default function ApiDocsPage() {"  
c += String.fromCharCode(10) + "  const [isLoading, setIsLoading] = useState(true);"  
c += String.fromCharCode(10) + "  useEffect(() => {"  
c += String.fromCharCode(10) + "    const timer = setTimeout(() => setIsLoading(false), 500);"  
c += String.fromCharCode(10) + "    return () => clearTimeout(timer);"  
c += String.fromCharCode(10) + "  }, []);"  
c += String.fromCharCode(10) + "  return (" 
c += String.fromCharCode(10) + "    <div className=\"api-docs-container\">"  
c += String.fromCharCode(10) + "      {isLoading && ("  
c += String.fromCharCode(10) + "        <div className=\"api-docs-loading\">"  
c += String.fromCharCode(10) + "          <div className=\"loading-spinner\"></div>"  
c += String.fromCharCode(10) + "          <p>Loading API documentation...</p>"  
c += String.fromCharCode(10) + "        </div>"  
c += String.fromCharCode(10) + "      )}" 
fs.writeFileSync("src/app/api-docs/page.tsx", c);  
