# Cloudflare Workers Configuration
# Documentation: https://developers.cloudflare.com/workers/

name = "baocaoluadao-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"
node_compat = true

# Account ID
account_id = "76810f76c3bf695a91848a81cb4f807a"

# Environment variables
[vars]
ENVIRONMENT = "production"

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "baocaoluadao-d1"
database_id = "e95728a8-5016-4adb-822f-02c66ffe789a"
