"'use client';"  
""  
"import React from 'react';"  
""  
"interface LineIconProps {"  
"  name: string;"  
"  className?: string;"  
"  size?: number;"  
"}"  
""  
"// Map of common icon names"  
"const iconMap: Record<string, string> = {"  
"  // Navigation"  
"  'home': 'lni-home',"  
"  'dashboard': 'lni-dashboard',"  
"  'menu': 'lni-menu',"  
"  'search': 'lni-search',"  
"  'close': 'lni-close',"  
"  'arrow-left': 'lni-arrow-left',"  
"  'arrow-right': 'lni-arrow-right',"  
"  'chevron-left': 'lni-chevron-left',"  
"  'chevron-right': 'lni-chevron-right'," 
